/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 BeautyInBloom.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/BeautyInBloom.gltf')
  return (
    <group {...props} dispose={null} scale={15}>
      <group position={[-0.09, 10.88, 0.12]} rotation={[1.7, 0, 0]} scale={[4.43, 5.28, 5.28]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane_2.geometry} material={materials['Scene_-_Root']} />
      </group>
      <mesh geometry={nodes.Easel_01a002__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={10} />
    </group>
  )
}

useGLTF.preload('/BeautyInBloom.gltf')
