/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Beetle.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Beetle.gltf')
  return (
    <group {...props} dispose={null} scale={12}>
      <group position={[0.03, 8.919, 0.035]} rotation={[Math.PI, 0.008, -Math.PI / 2]} scale={[0.074, 0.03, 0.074]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.bolt} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.metal} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials.white} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials.black} />
      </group>
      <mesh geometry={nodes.Plane003.geometry} material={materials.Beetle} position={[-0.018, 14.704, -0.455]} rotation={[1.689, 0, 0]} scale={[5.071, 1.28, 5.1]} />
    </group>
  )
}

useGLTF.preload('/Beetle.gltf')
