export const artData = [
    {
      id: 1,
      name: "BEAUTY IN BLOOM",
      description: "This piece of art exists within its true bohemian element...",
      imageUrl: "/Images/BeautyInBloom.jpg",
      size: "19 X 16 inches",
      medium: "acrylics",
      type: 'abstract',
      sizeRange: 'large',
      subjectMatter: 'portrait',
    },
    {
      id: 2,
      name: "EVERY SISTERHOOD HAS RULES",
      description: "This piece of modern art showcases the subtle strength...",
      imageUrl: "/Images/3Women.jpg",
      size: "5.3 x 8.3 inches",
      medium: "acrylics",
      type: 'abstract',
      sizeRange: 'large',
      subjectMatter: 'portrait',
    },
    {
      id: 3,
      name: "THE BEETLE",
      description: "This particular piece seeks to capture the sprightly spirit...",
      imageUrl: "/Images/Beetle.jpg",
      size: "16 x 16 inches",
      medium: "acrylics",
      type: 'surrealistic',
      sizeRange: 'large',
      subjectMatter: 'abstract',
    },
    {
      id: 4,
      name: "THE HUNGRY SIMPSON",
      description: "By utilising an array of vibrant colours, the Hungry Simpson...",
      imageUrl: "/Images/Simpson.jpg",
      size: "12 x 10 inches",
      medium: "acrylics",
      type: 'abstract',
      sizeRange: 'medium',
      subjectMatter: 'portrait',
    },
    {
      id: 5,
      name: "SANJAY DUTT",
      description: "This particular piece is a visual representation of an Indian actor...",
      imageUrl: "/Images/SanjayDutt.jpg",
      size: "24 x 16 inches",
      medium: "charcoal",
      type: 'realistic',
      sizeRange: 'large',
      subjectMatter: 'portrait',
    },
    {
      id: 6,
      name: "NORMAN REEDUS",
      description: "This is a realistic portrait of an American actor and model...",
      imageUrl: "/Images/Norman.jpg",
      size: "24 x 16 inches",
      medium: "charcoal",
      type: 'realistic',
      sizeRange: 'large',
      subjectMatter: 'portrait',
    },
    {
      id: 7,
      name: "CELESTIAL TIDE",
      description: "An asterism of stars spills across the night sky...",
      imageUrl: "/Images/BlueGalaxy.jpg",
      size: "4 x 4 inches",
      medium: "acrylics",
      type: 'surrealistic',
      sizeRange: 'small',
      subjectMatter: 'nature',
    },
    {
      id: 8,
      name: "FALLEN ANGELS",
      description: "This piece of art captures the beauty of a peaceful pink sky...",
      imageUrl: "/Images/PinkSky.jpg",
      size: "4 x 4 inches",
      medium: "acrylics",
      type: 'realistic',
      sizeRange: 'small',
      subjectMatter: 'nature',
    },
    {
      id: 9,
      name: "SHADES OF SPRING",
      description: "This artwork captures the various blazing colors of springtime...",
      imageUrl: "/Images/Flower.jpg",
      size: "4 x 4 inches",
      medium: "acrylics",
      type: 'abstract',
      sizeRange: 'small',
      subjectMatter: 'nature',
    },
    {
      id: 10,
      name: "UNNATURAL BEAUTY",
      description: "This painting embodies an overlap between natural and man-made...",
      imageUrl: "/Images/GoldenLeaf.jpg",
      size: "4 x 4 inches",
      medium: "acrylics",
      type: 'abstract',
      sizeRange: 'small',
      subjectMatter: 'nature',
    },
    {
      id: 11,
      name: "SAPPHIRE SYMPHONY",
      description: "The sapphire flowers in this piece have a little transparency...",
      imageUrl: "/Images/BlueFlower.jpg",
      size: "5.3 x 8.3 inches",
      medium: "water-colors",
      type: 'abstract',
      sizeRange: 'medium',
      subjectMatter: 'nature',
    },
    {
      id: 12,
      name: "TWO OF A KIND",
      description: "This artwork showcases two foxes trying to to hold onto each other...",
      imageUrl: "/Images/Fox.jpg",
      size: "5.3 x 8.3 inches",
      medium: "water-colors",
      type: 'abstract',
      sizeRange: 'medium',
      subjectMatter: 'nature',
    },
    {
      id: 13,
      name: "A HAPPY FACE",
      description: "This artwork seeks to capture the essence of a troubled character...",
      imageUrl: "/Images/Joker.jpg",
      size: "5.3 x 8.3 inches",
      medium: "poster-colors",
      type: 'abstract',
      sizeRange: 'medium',
      subjectMatter: 'portrait',
    },
    {
      id: 14,
      name: "DALÍ",
      description: "This abstracted piece of art captures the sharp-eyed expression...",
      imageUrl: "/Images/Dali.jpg",
      size: "18 x 18 inches",
      medium: "poster-colors",
      type: 'abstract',
      sizeRange: 'large',
      subjectMatter: 'portrait',
    },
    {
      id: 15,
      name: "THE HUNGRY SIMPSON",
      description: "By utilising an array of vibrant colours, the Hungry Simpson...",
      imageUrl: "/Images/Simpson.jpg",
      size: "12 x 10 inches",
      medium: "acrylics",
      type: 'abstract',
      sizeRange: 'medium',
      subjectMatter: 'portrait',
    }
  ];
  