/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Joker.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Joker.gltf')
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh castShadow receiveShadow geometry={nodes.Frame.geometry} material={materials.BlackMetal} rotation={[Math.PI / 2, 0, 0]} scale={1} />
      <mesh castShadow receiveShadow geometry={nodes.PaperMat.geometry} material={materials.PaperMat} rotation={[Math.PI / 2, 0, 0]} scale={1} />
      <mesh castShadow receiveShadow geometry={nodes.pic.geometry} material={materials.Pic} rotation={[Math.PI / 2, 0, 0]} scale={1} />
    </group>
  )
}

useGLTF.preload('/Joker.gltf')
