/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PracticeGallery(props) {
  const { nodes, materials } = useGLTF('/practice-gallery.glb')
  return (
      <group scale={[5,5,5]}{...props} dispose={null}>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lights.geometry}
            material={materials.Art_Room1}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
        />
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Art_Room.geometry}
            material={materials.Art_Room1}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
        />
        <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Material} />
      </group>
  )
}