/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const PracticeGallery = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/practicegallery3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lights.geometry}
        material={materials.Art_Room1}
        position={[-0.053, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group position={[-0.053, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials.Art_Room1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials['Material.013']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Art_Room002.geometry}
        material={materials['Material.010']}
        position={[-0.053, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group
        position={[-13.866, 2.104, 6.453]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={2.301}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials['Black wod']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-13.866, 2.104, 3.623]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={2.301}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials['Black wod']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group  ref={ref} position={[-6.011, 2.142, 10.137]} rotation={[Math.PI / 2, 0, Math.PI]} scale={2.659}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials['Tiger wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_2.geometry}
          material={materials['Material.004']}
        />
      </group>
      <group
        position={[6.789, 2.104, 10.14]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[1.783, 2.301, 1.783]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials['Back wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={materials['Material.008']}
        />
      </group>
      <group
        position={[9.185, 2.104, 10.14]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[1.783, 2.301, 1.783]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_2.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group
        position={[-0.451, 2.104, 10.14]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[3.032, 2.301, 1.507]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group
        position={[4.185, 2.104, 10.14]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[1.783, 2.301, 1.783]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_2.geometry}
          material={materials['Material.006']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials.david}
        position={[-6.203, 2.558, -10.137]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.934}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['colored-david']}
        position={[-8.607, 2.565, -10.137]}
        rotation={[Math.PI / 2, -Math.PI / 3, Math.PI]}
        scale={0.934}
      />
      <group
        position={[-9.289, 2.104, 0.678]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.777, 2.301, 1.777]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_2.geometry}
          material={materials['Material.009']}
        />
      </group>
      <group
        position={[-2.303, 2.104, -10.137]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.161, 2.301, 2.161]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials.daryl}
        />
      </group>
      <group
        position={[0.64, 2.104, -10.137]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.161, 2.301, 2.161]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_1.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_2.geometry}
          material={materials['adheera-painting']}
        />
      </group>
      <group
        position={[-13.659, 2.104, -7.188]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.783, 2.301, 1.783]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_2.geometry}
          material={materials['Material.012']}
        />
      </group>
      <group
        position={[1.122, 2.104, -0.947]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[3.016, 2, 3.016]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_1.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_2.geometry}
          material={materials.bunny}
        />
      </group>
      <group position={[-9.995, 2.104, 10.137]} rotation={[Math.PI / 2, 0, Math.PI]} scale={2.301}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_1.geometry}
          material={materials['whale wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_2.geometry}
          material={materials['Material.011']}
        />
      </group>
      <group
        position={[-13.659, 2.104, -2.794]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.783, 2.301, 1.783]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_1.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_2.geometry}
          material={materials['Material.012']}
        />
      </group>
      <group
        position={[-13.659, 2.104, -5.015]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.783, 2.301, 1.783]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={materials['Black wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_1.geometry}
          material={materials['Material.012']}
        />
      </group>
    </group>
  )
});

useGLTF.preload('/practicegallery3.glb')