/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 practice-gallery.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PracticeGallery(props) {
  const { nodes, materials } = useGLTF('./practice-gallery.glb')
  return (
    <group {...props} dispose={null}> 
      <mesh geometry={nodes.Lights.geometry} material={materials.Art_Room1} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials.Art_Room1} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/practice-gallery.glb')
